### ISSUE TITLE
[BUG] Path exclusion doesn't work as expected with predefined paths

### ISSUE THREAD

**Issue by pkchv** [iamolegga/nestjs-pino#192]
**What is the current behavior?**

Implementation of route exclusion (see [#122 ](https://github.com/iamolegga/nestjs-pino/issues/122#issuecomment-567157358)) does not allow conditional exclusion of predefined paths without explicitly specyfing all of the applications controllers in `forRoutes` attribute.  This issue is caused by a known limitation of Nest interoperability with functional middlewares (please see [nestjs #853](https://github.com/nestjs/nest/issues/853#issuecomment-420282567) for more details).

**Please provide the steps to reproduce.**

Nestjs-pino module configuration like the one specified below doesn't work as expected, that is GET requests to `/live` and `/ready` paths still leave log traces in applications stdout.

```typescript
{
    forRoutes: [{ path: '*', method: RequestMethod.ALL }],
    exclude: [
        { path: 'live', method: RequestMethod.GET },
        { path: 'ready', method: RequestMethod.GET },
    ],
}
```

**What is the expected behavior?**

This is not explicitly stated anywhere, but a good implementation would allow conditional exclusion of predefined routes from request logging without explicitly passing all of the apps controllers, as this approach is cumbersome and error prone. Wrapping logger middleware with path exclusion logic as suggested in `#853` might be a good solution.

**Please mention other relevant information such as Node.js version and Operating System.**

|  package | version |
--- | ----
node | `v12`
nest | `v6+` 
nestjs-pino | `v1.1.3`

**Comment by iamolegga** [comment]
Just a few word about `doesn't work as expected`: actually it works as expected and as described [here](https://github.com/iamolegga/nestjs-pino#configuration-params) in related props. It's even covered with tests. Your problem refers to **limitations of framework itself**. So this is not the bug of current library, and I'm closing this issue.

If you want to resolve limitations of framework you can open **feature request** [here](https://github.com/iamolegga/nestjs-pino/issues/new/choose), because things that you want is extra behaviour. Then maybe I can invest my time to work this out.

Cheers
