### ISSUE TITLE
[QUESTION]How to use in Guards Interceptors...

### ISSUE THREAD

**Issue by zxchcyc** [iamolegga/nestjs-pino#301]
sorry,  I am a newbie in nestjs, How to use in Guards Interceptors Pipes Exception filters Middleware, can you provide a demo.

**Comment by iamolegga** [comment]
Just inject class as you do with any other services in guards, interceptors, pipes, exception filters, middleware. Sometimes you need to use https://docs.nestjs.com/providers#property-based-injection, but in common it's the same as you do it in controllers and services.

For now, I'm closing this question, because it's general and related more to NestJS than this project. But if you are faced with some concrete problems feel free to provide your code here.
