### ISSUE TITLE
[QUESTION] Logging ExecutionContext's data

### ISSUE THREAD

**Issue by andrucz** [iamolegga/nestjs-pino#347]
Does this library support logging the user associated with the request?

My application uses a custom `@nestjs/passport` strategy to handle authentication:

```
class MyStrategy extends PassportStrategy(BasicStrategy, 'custom') {
  async validate(username: string, password: string): Promise<IUser> {...}
}
```

When I need to access the user in a guard, for example, I do the following:

```
class PermissionGuard implements CanActivate {
  canActivate(context: ExecutionContext) {
    const args = context.switchToHttp();

    const request = args.getRequest();
    const user = request.user as IUser;
    ...
  }
}
```

Is there a way to automatically add the user to the log context?

**Comment by iamolegga** [comment]
that's just regular middlewares order. You need set user somehow before pino module set it's own middlewares, and configure log to add custom property. look at pino-http parameters.

I guess main problem would be calibrate modules order for proper middlewares order, because there is no guaranty in nestjs for middlewares order set on different modules
