### ISSUE TITLE
[QUESTION] How to add userId for each authenticated request

### ISSUE THREAD

**Issue by vladiulianbogdan** [iamolegga/nestjs-pino#433]
Hello,

I am using your library in my project. Thanks for your work, it is really helpful!

We are using a Passport local strategy for authentication (https://docs.nestjs.com/security/authentication#implementing-passport-local). If the authentication is performed correctly, the `user` object will be added on the `request` object that it will be later passed to the controllers.

What I would like to do is to add the `userId` value to each request information that is bundled together with each log. It seems that the serializer methods are called before this auth layer is called and I did not find a way to do this in the documentation.

Do you have any advice on how to implement this?

Thank you!

**Comment by iamolegga** [comment]
Hi, for such purpose I've created [this library](https://github.com/iamolegga/nestjs-configure-after), because nest doesn't have guarantee of modules registration and middlewares order, you can see [discussion for same problem of middlewares order in another my package](https://github.com/iamolegga/nestjs-session/issues/276). All you need is wrap this module in another one with extra decorator, and add one to your passport/auth/whatever module.

and the second part is you need to find [specific option](https://github.com/pinojs/pino/blob/master/docs/api.md#options-object) to add new properties to logs

Feel free to ping me with your code exmaples

**Comment by EdByrnee** [comment]
Did you manage to find a solution for this?

**Comment by vladiulianbogdan** [comment]
I haven't tried yet what iamolegga suggested, but I will do it as soon as possible and I will let you know.

**Comment by MikeKoval** [comment]
@vladiulianbogdan can you share snippet how you resolved that issue with decorators pls?
do you use logger.assign inside decorator or at controller itself? if in decorator, how do you pass it there?
