### ISSUE TITLE
[QUESTION] Change timestamp format

### ISSUE THREAD

**Issue by aerdnach** [iamolegga/nestjs-pino#449]
Hi, I'm trying to change timestamp format. This is what I've done in my configuration accordingly to [docs](https://github.com/pinojs/pino/blob/master/docs/api.md#options): 

```javascript
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { v4 as uuid } from 'uuid';
import { LoggerModule } from 'nestjs-pino';
import pino from 'pino';

@Module({
  imports: [
    LoggerModule.forRoot({
      pinoHttp: [
        {
          useLevel: 'info',
          genReqId: () => uuid(),
          serializers: {
            timestamp: () => `,"time":"${new Date(Date.now()).toISOString()}"`,
          },
        },
        pino.destination('pino.log'),
      ],
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

But when logging i still see default format (Milliseconds since Unix epoch).

What am I doing wrong?

Thanks

**Comment by iamolegga** [comment]
First of all this is more related to `pino-http`, because all options are passed as is. I can suggest to check [pino-http options](https://github.com/pinojs/pino-http#pinohttpopts-stream), maybe `wrapSerializers` is what you need?

Maybe best advise here is try setup `pino-http` in basic http server first. Or ask a question if it doesn't work in related repo.

So I'm closing this. If there are bugs when passing params to underlying library feel free to reopen.
