### ISSUE TITLE
[FEATURE REQUEST] Adding Additional Request Scoped Context

### ISSUE THREAD

**Issue by goofiw** [iamolegga/nestjs-pino#462]
Is it possible to add fields to the logged JSON object after the logger is configured?

For example, I'd like to add a userId and organizationId to each log after it's gone through my authorization guard for the duration of the request.

maybe something inside my auth guard like `this.logger.addContext({ userId, orgId});`. Then all logs for that request include the additional context.

I thought about extending the injected PinoLogger class, but don't want to include a RequestScoped injectable essentially everywhere.

**Comment by iamolegga** [comment]
From pino docs it looks like there is only one way to add more fields in logger: using child logger (maybe you know some other way?). But this requires replacement of base logger in continuation local storage. Technically looks like this could be possible. But I would prefer `addFields` or `assign` instead of `addContext` because `context` word is already using for another thing. I'll convert this question to feature request 👍

**Comment by iamolegga** [comment]
I've been working a lot with microservices a while ago and just thought that this could be really useful here too, because we don't have same logging middleware mechanism for event receivers in microservices as we have for http server. So yeah, that could be really useful. I hope I can find time for this in nearest future 🤞

**Comment by hamxabaig** [comment]
I think this would be perfect use-case for this library. I integrated this in our production app to get better logs with request trace ids. Having user information in request will really be a game changer in terms of Dev Xp.

**Comment by goofiw** [comment]
Following up on this - I'm not sure I'll get to do it with this project.

Having all the request details on every log is more than we are after, so I think we might roll our on and add a traceId along with user info. (Thank you so much for pointing out out async-hooks, that's how I plan to do it)

**Comment by iamolegga** [comment]
Hi, just released v2.1.0, please check out [the docs](https://github.com/iamolegga/nestjs-pino#assign-extra-fields-for-future-calls). Works for http request scope so far. Will think later if I can add the same for microservices

**Comment by gitSambhal** [comment]
@iamolegga Any updates for microservice? I am getting `PinoLogger: unable to assign extra fields out of request scope`  with Pubsub.

**Comment by iamolegga** [comment]
@gitSambhal there is single open pinned issue already, you can subscribe and wait or fork and implement
