### ISSUE TITLE
[FEATURE REQUEST] Catch initialization errors.

### ISSUE THREAD

**Issue by thekip** [iamolegga/nestjs-pino#789]
If error happend somewhere in modules initialization before `.useLogger()` call, error will be reported by standart logger. 

```ts
const app = await NestFactory.create(AppModule, { bufferLogs: true }); 
// error is thrown in NestFactory.create, next line will never be executed
app.useLogger(app.get(NestPinoLogger));
```

There are many reasons why application might not be created, for example not provided module in DI or circular dependency.

The easiest way to simulate this is write this in App's providers: 

```ts

@Module({
  imports: [],
  providers: [
    {
      provide: APP_INTERCEPTOR,
      useFactory: () => {throw new Error();},
    },
  ],
})
export class AppModule {}
```

**Describe the solution you'd like**
I would like to catch all errors. For that, we can proably use `logger` parameter of  `NestFactory.create()` method:
```ts
const app = await NestFactory.create(AppModule, { logger: new NestPinoLogger() });
```
I assume (i didn't test it yet) that this should catch initialization errors as well. Unfortunately code written above is incorrect, because `new NestPinoLogger()` requires and additional services in the constructor and can not be instantiated this way. 

So proposition is create a simplified version just for this case which can be used a s default logger until DI tree is compiled or refactor `NestPinoLogger` to be instantiated this way.

**Comment by iamolegga** [comment]
This is a limitation of the framework, and that's not possible to build the logger properly without DI, as it will not have access to the config. From my point of view, this is a good tradeoff (fallback to standard logger) between complexity and dx. Closing, as with the current API it's not possible to build properly, and on the next step, someone will open the new issue about misconfigured _simplified_ version, but that can not be solved without DI.

But you can always use your own `pino` instance in `NestFactory.create()` params

**Comment by smnbbrv** [comment]
For anyone looking for a quick solution:

```ts
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter({
      trustProxy: true,
    }),
    {
      logger: new NestPinoLogger(new PinoLogger({}), {}),
    },
  );
```

You can also omit  `bufferLogs: true` that can also affect the logs you see.

@iamolegga thank you for the time and your work you invest into this project, I really appreciate what you are doing, however I cannot understand why such a clear problem does not deserve any attention. If I can't see the problems on application startup, that's a total disaster and nearly impossible to debug.

**Comment by iamolegga** [comment]
@smnbbrv thanks for your kind words. Speaking about the current issue I'm not sure it's still actual, for example in my current project I've removed the built-in CqrsModule which provides CommandBus, and got a nice error message :

```
[Nest] 52490  - 05.10.2023, 12:59:49   ERROR [ExceptionHandler] Nest can't resolve dependencies of the MyController (?). Please make sure that the argument CommandBus at index [0] is available in the MyModule context.

Potential solutions:
- Is MyModule a valid NestJS module?
- If CommandBus is a provider, is it part of the current MyModule?
- If CommandBus is exported from a separate @Module, is that module imported within MyModule?
  @Module({
    imports: [ /* the Module containing CommandBus */ ]
  })

Error: Nest can't resolve dependencies of the MyController (?). Please make sure that the argument CommandBus at index [0] is available in the MyModule context.

Potential solutions:
- Is MyModule a valid NestJS module?
- If CommandBus is a provider, is it part of the current MyModule?
- If CommandBus is exported from a separate @Module, is that module imported within MyModule?
  @Module({
    imports: [ /* the Module containing CommandBus */ ]
  })

    at Injector.lookupComponentInParentModules (path-to-project/node_modules/@nestjs/core/injector/injector.js:254:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Injector.resolveComponentInstance (path-to-project/node_modules/@nestjs/core/injector/injector.js:207:33)
    at resolveParam (path-to-project/node_modules/@nestjs/core/injector/injector.js:128:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (path-to-project/node_modules/@nestjs/core/injector/injector.js:143:27)
    at Injector.loadInstance (path-to-project/node_modules/@nestjs/core/injector/injector.js:70:13)
    at Injector.loadController (path-to-project/node_modules/@nestjs/core/injector/injector.js:88:9)
    at path-to-project/node_modules/@nestjs/core/injector/instance-loader.js:68:13
    at async Promise.all (index 0)
```

```ts
  const app = await NestFactory.create(MainModule, {
    bufferLogs: true,
  });
  app.useLogger(app.get(Logger));
```

That's nestjs@10, seems like such errors are handled by default logger which I believe is good enough for that case

**Comment by smnbbrv** [comment]
@iamolegga the circular dependencies are shown for me as well. The issue I face goes in the same direction as the original one however it's not really the same thing.

Example: there is a redis connection that's about to be established in one of the services and this connection actually defines whether the application can properly function at all. That's why the connection is checked in async `onModuleInit` hook and it only gets resolved if the connection is successful.

When, however, redis is unreachable or the password is incorrect (and it's quite often the case in production), the connection is not being established and redis client infinitely tries to reconnect while properly throwing the error log messages.

The LoggerModule as well as the Logger.flush are blocked because `onModuleInit` is not getting resolved. `bufferLogs: true` actually prevents the logs from being directly printed and as a result there are literally no logs printed. That is really confusing and nearly impossible to debug.

Probably I can change the way the application starts up and stop checking the connection. But the combination of pending application (thus blocked  `LoggerModule`) and the enabled `bufferLogs` param seem to inavoidably cause issues of similar kind.

To consistently resolve it, as it seems, the only way is a direct construction of the logger instance and providing it to the factory.

**Comment by iamolegga** [comment]
What's the behavior of other logger implementations in that case? I'm wondering if this is a bug of the current library

**Comment by smnbbrv** [comment]
I haven't really tried anything since the implementation of custom logger from https://docs.nestjs.com/techniques/logger#custom-implementation is quite straightforward. The approach this library goes is described on the same page https://docs.nestjs.com/techniques/logger#injecting-a-custom-logger

I assume the primary difference between the first and second way is only the ability to inject a config service.

**Comment by iamolegga** [comment]
Sorry, I didn't get it. My question is: would there be the same error if instead of the current library use a basic custom logger which depends on di. If so, this is a limitation/bug of the framework.
